DjangoSnap/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from DjangoSnap.settings import DEBUG
from django.conf.urls import url
from django.views.generic.base import RedirectView
import snap



urlpatterns = [
    #path('accounts/login/', auth_views.LoginView.as_view()),
    
     url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
     path('accounts/', include('django.contrib.auth.urls')),
     path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html')),
    path('admin/', admin.site.urls),
    path('snap/',include('snap.urls')),
    path('boucles/',include('visualisation_boucles.urls')),
    path('celery/',include('rendu_celery.urls')),
    path('login/',snap.views.login_redirect),
    path('logout/',snap.views.logout_view,name='logout'),
    path(r'',auth_views.LoginView.as_view()),
         #RedirectView.as_view(url='/accounts/login/')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if DEBUG:
    urlpatterns=urlpatterns+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

snap/urls.py
'''
Created on 4 déc. 2017

@author: duff
'''
from django.urls import path

from . import views, reconstitution
from rest_framework.routers import DefaultRouter
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

admin.site.site_header = 'Snap4Gironde'
admin.site.site_title='Snap4Gironde'
router = DefaultRouter()
router.register(r'progs', views.ProgrammeBaseViewset)
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'evenement',views.EvenementViewset)
router.register(r'epr',views.EvenementEPRViewset)
router.register(r'env',views.EvenementENVViewset)
router.register(r'spr',views.EvenementSPRViewset)
router.register(r'spropen',views.EvenementSPROpenViewset)
router.register(r'spr/block',views.BlockViewSet)

urlpatterns = [
    path('prof',views.connection_prof,name='accueil_prof'),
    path('choix_base',views.choix_base,name='choix_base'),
    path('eleves_base',views.eleves_base),
    path('eleve_base',views.eleve_base),
    path('test',views.testsnap,name='snaptest'),    
    path('pageref',views.pageref),
     path('pagedon',views.pagedon),
     path('ups',views.simple_upload),  
     path('up',views.model_form_upload),
    # path('upload',views.upload),
    path('fichier',views.return_fichier),
    path('fichier/<int:file_id>', views.return_fichier_eleve),
    #path('cd',views.current_datetime),
    path('cd',views.return_files),    
    path('liste/',views.liste),
    path('liste/<str:nom>/',views.liste),
    path('sessions',views.listeSessions),
    path('session/<str:id>/',views.session),
    path('opens',views.listeOpens),
    #path('open/',views.listeOpen),
    #path('open/<str:id>/',views.listeOpen),
    path('cyto',views.cyto),
    path('cyto/<str:id>/',views.cyto,),
    path('cyto2',views.cyto3),
    path('tb',views.testblock),
    path('tb/<str:id>/',views.testblock),    
    #path('toliste',views.listeblock),
    path('toliste',reconstitution.listeblock),
    path('toliste/<str:id>/',views.listeblock),
    path('snps',reconstitution.listesnaps),
    path('snps/<str:id>/',reconstitution.listesnaps),
    path('d33',TemplateView.as_view(template_name='index.html')),
    path('d3',TemplateView.as_view(template_name='representation.html')),
     path('c2',TemplateView.as_view(template_name='testcyto2.html')),
     path('ajax',views.testAjax),
     path('tr/<str:id>/',views.testReconstruit),
     path('testr/<int:id>',views.testEnvoi),
    ]

urlpatterns += [
    url(r'^', include(router.urls))
]
urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]

snap/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import validate_comma_separated_integer_list
from django.db.models import signals

import os
from django.core.files.storage import default_storage
from django.db.models import FileField
from snap.objets import BlockSnap
from django.db.models.fields import related




class Classe(models.Model):
    nom= models.CharField(max_length=10)
    def __str__(self):
        return '%s' % self.nom

class Eleve(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    classe =models.ForeignKey(Classe,null=True,on_delete=models.SET_NULL)
    prg=models.ForeignKey('ProgrammeBase',null=True,blank=True,
                          on_delete=models.SET_NULL,verbose_name='Programme de la séance')
    def __str__(self):
        return '%s' % self.user.username



def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class ProgrammeBase(models.Model):
    #Nom du programme de base
    user=models.ForeignKey(User,on_delete=models.CASCADE) #utilisateur
    nom=models.CharField(max_length=50,null=False,blank=False,unique=True)
    description = models.CharField(max_length=255, blank=True)
    file=models.FileField(upload_to=user_directory_path)
    creation=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return '%s (%s)' % (self.nom,self.user_id)

class Evenement(models.Model):
    ENVIRONNEMENT='ENV'
    ETAT_PROGRAMME='EPR'
    STRUCTURE_PROGRAMME='SPR'
    SCRIPT='SCR'
    AUTRE='AUT'
    TYPE_EVENEMENT_CHOICES=(
        (ENVIRONNEMENT,'Environnement'),
        (ETAT_PROGRAMME,'Etat du Programme'),
        (STRUCTURE_PROGRAMME,'Structure du Programme'),
        (SCRIPT,'Script'),
        (AUTRE,'Autre évènement'),
        )
    user=models.ForeignKey(User,on_delete=models.CASCADE) #utilisateur
    session_key=models.CharField(max_length=40,null=True)
    programme=models.ForeignKey(ProgrammeBase,null=True, on_delete=models.SET_NULL) #programme de base chargé
    type=models.CharField(max_length=3,choices=TYPE_EVENEMENT_CHOICES, default=AUTRE) #type d'évènement
    time=models.BigIntegerField() #Temps (local à Snap) de l'évènement
    numero=models.IntegerField() #numero d'ordre de l'évènement, indépendant du type
    creation=models.DateTimeField(auto_now_add=True)
    def toD3(self):
        res={}
        res['id']=self.id
        res['type']=self.type
        res['type_display']=self.get_type_display()
        res['numero']=self.numero
        res['time']=self.time
        return res

    def getEvenementType(self):
        """
        renvoi le sous evenement (de type ENV, SPR ou EPR)
        """
        if self.type==self.ENVIRONNEMENT: return self.environnement.all()[0]
        elif self.type==self.ETAT_PROGRAMME: return self.evenementepr.all()[0]
        elif self.type==self.STRUCTURE_PROGRAMME: return self.evenementspr.all()[0]
        else:
            raise KeyError(u'Type evenement inconnu (%s)' % self.type)

    def __str__(self):
        #return '(%s) %s n°%s' % (self.user,self.get_type_display(),self.numero)
        return '(%s) %s n°%s %s' % (self.user,self.get_type_display(),self.numero,self.getEvenementType().type)

    class Meta:
        ordering=('-creation',)

class EvenementENV(models.Model):
    """
        Evenement lié à la modification de l'environnement
        (chargement/sauvegarde, clics divers )
    """
    ENV_CHOICES=(
        ('LANCE','Lancement (ou relancement) de Snap'),
        ('MENU', 'Clic Menu'),
        ('PARAM','Clic Menu paramètres'),
        ('NEW','Nouveau programme vide'),
        ('LOBA','Chargement programme de Base'), #nom dans detail, id dans valueInt (à la création)
        ('LOVER','Chargement d\'une version sauvegardée'), # id dans detail
        ('IMPORT','Importation fichier local'), # normalement suivi d'un EPR  LOAD (pas encore) ou/et SPR OPEN
        ('EXPORT','Exportation fichier local'),
        ('FULL','Plein écran'),
        ('APP','Ecran application'),
        ('SSCRN','Ecran réduit'),
        ('NSCRN','Ecran normal'),
        ('SBS','Pas à pas'),
        ('GREEN','Clic Green Flag'),
        ('PAUSE','Clic Mise en pause'),
        ('REPR','Clic Reprise'),
        ('STOP','Clic Stop'),
        ('KEY','Evènement Clavier'),
        ('AFFBL','Affichage Blocs'), # category  detail?
        ('AFFVAR','Affichage ou non Variable'), #avec nom en valueChar et vrai.faux en bool et valeur en detail
        ('BUBBLE','Affichage bulle'), #id dans valueInt (si pas connue c'est un block de la palette,
                                      #text dans detail, selector dans valueChar
        ('DROPEX','Drop dans la palette (suppression)'), # normalement suivi d'un évènement suppression
        #('UNDROP','Undrop'), #origine dans detail
        #('REDROP','Redrop'),
        ('DUPLIC','Duplication'), #menu dupliquer, detail=JMLid(orig), valueInt=JMLid(copie) , valueBool=vrai si un seul bloc
        ('POPUP','Ouverture popup'),
        ('AUTRE','(Non identifié)'),
        )
    evenement=models.ForeignKey(Evenement,on_delete=models.CASCADE,related_name='environnement')
    type=models.CharField(max_length=6,choices=ENV_CHOICES, default='AUTRE') #type d'évènement
    click=models.BooleanField(default=False)
    key=models.BooleanField(default=False)
    detail=models.TextField(null=True,blank=True)
    valueBool=models.NullBooleanField(null=True)
    valueInt=models.BigIntegerField(null=True)
    valueChar=models.CharField(max_length=30,null=True,blank=True)
    #block=models.ForeignKey(Block,on_delete=models.CASCADE)

    def toD3(self):
        """rendu json pour d3.js"""
        res={}
        res['d3id']='%s_%s' % (self.evenement.id, self.id) #id pour les data de d3.js
        res['id']=self.id
        res["evenement"]=self.evenement.toD3()
        res['type']=self.type
        res['type_display']=self.get_type_display()
        res['detail']=self.detail
        return res

    def __str__(self):
        return '(%s) %s: %s %s' % (self.evenement,self.get_type_display(),self.detail,"(clic)" if (self.click) else "")

    class Meta:
        ordering=('-evenement__time',)
        get_latest_by=['evenement__time',]

class SnapProcess(models.Model):
    """
        Process de Snap
    """
    receiver=models.CharField(max_length=30,null=True) #lutin en cause
    topBlockSelector=models.CharField(max_length=30,null=True,) #slector du bloc du haut
    topBlockId=models.PositiveIntegerField(null=True) # id du bloc du haut
    click=models.BooleanField(default=False) #lancement arret sur clic du script
    errorFlag=models.BooleanField(default=False)
    class Meta:
        abstract = True
        ordering = ['receiver','+topBlockId']

def userSnapShot(instance, filename):
        # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
        return 'user_{0}/SnapShots/{1}'.format(instance.evenement.user.id, filename)
class SnapSnapShot(models.Model):
    evenement=models.ForeignKey(Evenement,on_delete=models.CASCADE,related_name='image')
    image=models.ImageField(upload_to=userSnapShot,blank=True)

    def delete(self,*args,**kwargs):
        #ne marche pas sur un delete ou sur un queryset.delete
        # You have to prepare what you need before delete the model
        storage, path = self.image.storage, self.image.path
        # Delete the model before the file
        super(SnapSnapShot, self).delete(*args, **kwargs)
        # Delete the file after the model
        storage.delete(path)




class EvenementEPR(SnapProcess):
    """
        Evenement lié à la modification de l'état du programme
    """
    EPR_CHOICES=(
        ('NEW','Nouveau programme vide'),
        ('LOAD','Programme chargé'), # id dans detail si LOVER, nom du prg de base si LOBA
        ('SAVE','Programme sauvegardé'),
        ('SAVEO','Sauvegarde automatique'), # time(bigint)  dans detail
        ('START','Lancement'),
        ('STOP','Arrêt'), #arrêt manuel
        ('FIN','Terminaison'),
        ('PAUSE','Pause'),
        ('REPR','Reprise'),
        ('ERR','Erreur'),
        ('ASK','Demande d\'une entrée utilisateur'),
        ('ANSW','Entrée de l\'utilisateur'), #strockée dans detail
        ('SNP','Snapshot'), #id de l'image dans detail
        ('AUTRE','(Non identifié)'),
        )
    evenement=models.ForeignKey(Evenement,on_delete=models.CASCADE,related_name='evenementepr')
    type=models.CharField(max_length=5,choices=EPR_CHOICES, default='AUTRE') #type d'évènement
    detail=models.TextField(null=True,blank=True)
    processes=models.TextField(null=True,blank=True) # liste des process en cours, sous la forme "id-nom"

    def toD3(self):
        """rendu json pour d3.js"""
        res={}
        res['d3id']='%s_%s' % (self.evenement.id, self.id) #id pour les data de d3.js
        res['id']=self.id
        res["evenement"]=self.evenement.toD3()
        res['type']=self.type
        res['type_display']=self.get_type_display()
        res['detail']=self.detail
        return res

    def __str__(self):
        return '(%s) %s: %s %s' % (self.evenement,self.get_type_display(),self.detail,"(clic)" if (self.click) else "")

    class Meta:
        ordering=('-evenement__time',)
        get_latest_by=['evenement__time',]

class BlockInput(models.Model):
    """
        Entrée d'une brique
    """
    JMLid=models.IntegerField(null=True) #JMLid du block en cause
    typeMorph=models.CharField(max_length=30,null=True,blank=True)
    rang=models.IntegerField(default=0) #rang de l'entrée
    contenu=models.CharField(max_length=50,null=True,blank=True)#contenu de l'entrée
    isNumeric=models.BooleanField(default=True)
    isPredicate=models.BooleanField(default=False)

    class Meta:
        ordering = ['rang']

    def __str__(self):
        return '%s, %s (JML %s)' % (self.rang,self.contenu,self.JMLid)


class EvenementSPR(models.Model):
    """

snap/forms.py
from django import forms
from snap.models import Document, ProgrammeBase
from django.forms.models import ModelForm

class ExportXMLForm(forms.Form):
    base=forms.BooleanField(initial=False, required=False)
    autosave=forms.BooleanField(initial=False, required=False)
    description=forms.CharField(max_length=255, required=False)
    nom=forms.CharField(max_length=50)
    document=forms.FileField()
    
class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('description', 'document',  )
    
class ProgBaseForm(forms.ModelForm):
    class Meta:
        model=ProgrammeBase
        fields=('nom','file',)

snap/templates/don.html
<p>{{autre}}: {% for k in data %} {{k.time}} {{k.action}}:{{k.blockSpec}}--{% endfor %}</p>  

snap/templates/file_user_prof.html
{% load static %}
<script src="{% static 'snap/js/jquery-3.2.1.min.js' %}"></script> 
        <script
              src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
              integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
              crossorigin="anonymous"></script>
              <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
 <script src="{% static 'visualisation_boucles/js/d3.min.js' %}"></script>
<script src="{% static 'visualisation_boucles/js/crossfilter.min.js' %}"></script>
<script src="{% static 'visualisation_boucles/js/dc.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'visualisation_boucles/js/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'visualisation_boucles/js/dc.min.css' %}">
<h3>Fichiers sauvegardés ({{user.username}})</h3>

<div id="selectClasse">    
</div>
<div id="selectEleve">   
</div>
<div id="selectFic">   
</div>
<script>
var selectClasse=dc.selectMenu("#selectClasse"),
    selectEleve=dc.selectMenu("#selectEleve"),
    selectFic=dc.selectMenu("#selectFic");
    
var data=[

{% for file in files%}
{ 'classe':"{{file.user.eleve.classe.nom|default:'prof'}}",
    'user':"{{file.user.username}}",
    'nom': "{{file.description}}", 
    'date':"{{file.uploaded_at}}",
    "td":"{{file.uploaded_at|date:'c'}}",
    'id':"{{file.id}}",
    'autosave':("{{file.autosave}}"=="True")
    
},
{%endfor%}
]
//data=data.sort((a,b)=>a-b)
//console.log("data",data)
var sepFic="_-_"
var ndx=crossfilter(data), ngdx=crossfilter(data)    
    classeDim=ndx.dimension(d=>d.classe),
    eleveDim=ndx.dimension(d=>d.user),
    ficDim=ndx.dimension(d=>d.id+sepFic+d.nom+sepFic+d.date+sepFic+d.autosave+sepFic+d.td)
 
selectClasse
   .dimension(classeDim)
   .group(classeDim.group())
   //.promptText("toutes les classes")
   .numberVisible(16)
   .title(d=>(d.key==''?"prof":d.key)+" ("+d.value+")")
selectEleve
   .dimension(eleveDim)
   .group(eleveDim.group())
   .numberVisible(16)
   .title(d=>d.key+" ("+d.value+")")
selectFic
   .dimension(ficDim) 
   .group(ficDim.group())
   .title(function(d) {
       let s=d.key.split(sepFic)
       return s[1]+" ("+(s[3]=="true"?"auto, ":"")+s[2]+")"
   })
   .numberVisible(16)
    .controlsUseVisibility(true)
    .order(function (a,b) {
        let sa=a.key.split(sepFic)[4]
        let sb=b.key.split(sepFic)[4]         
    return sa > sb ? -1 : sb > sa ? 1 : 0;
    })
dc.renderAll()
</script>

snap/templates/index.html
<!DOCTYPE html>
<meta charset="utf-8">
{% load static %}
<head>
<link rel="stylesheet" type="text/css" href="{% static 'snap/js/rendu.css' %}" >
</head>
<body>
	<script src="https://d3js.org/d3.v4.min.js"></script>
	<script src="{% static 'snap/js/rendu.js' %}"></script>
    
    
	<h3>Actions suite à une ouverture de programme</h3>

  <label for="eleves">Choisir un élève: </label>
  <select  list="listeEleves" id="selectEleves"></select>
  <datalist id="listeEleves">  
  </datalist>
  <div id="session">
  <label for="session">Choisir une session: </label>
  <select  list="listeSessions" id="selectSessions"></select>
  <datalist id="listeSessions">  
  </datalist>
  </div>
  
  
  <div id="resultats">
    <div id="affichage"></div>
    <div id="actions"></div>
    <div id="etapes"></div> 
  </div>
  </body>

snap/templates/liste_entree.html
{% load static %}
<style>
tr.HatBlockMorph {
color:green;
}
tr.CommandBlockMorph {
color: blue;
}
tr.CSlotMorph {
color: grey;
font-size: 70%;
}
tr.ReporterBlockMorph {
color: purple;
}
.u {
    text-decoration: none;
    /*padding: 20px 0;*/
    border: 1px dotted blue;    
    
}
.no-u {
    text-decoration: underline;
    display: inline;
}
.u.nochange {
    opacity:0.5;
    }
.u.change {
    opacity:1;
    background-color : yellowgreen ;
    }
.u span {
    text-decoration: none;
    display: inline-block;
   
}
span.passe {
color:DarkSlateGray ;
}
span.changed {
    text-decoration: none;
    color: green;
}
span.added {
    text-decoration: overline;
    color:red;
    opacity: 1;
}
span.replaced-silent {
    text-decoration: underline;
    color:red;
    opacity: 1;
}
span.SPR_NEW, span.init {
    color:blue;
    opacity: 1;
}
span.DROPPED {
    color:blue;
    text-decoration: underline;
    opacity: 1;
}
span.SPR_DEL {
    color:grey;
    text-decoration:line-through red;
    opacity: 1;
    
}
span.ASK {
    color:blue;    
}
span.ANSW {
    font-size: 150%;
    color:red;    
}


</style>
<h1>{{infos.user}}</h1>
<h2>Suivi des paramètres</h2>
<h3 title="{{infos.tooltip}}">{{infos.type}}</h3>
<p>le {{infos.date}}</p>

<table align="left">
<tr><td>Temps</td>
{% for c in commandes.0.snap %}
<td>block {{c.JMLid}}</td>
{%endfor%}
</tr>
{% for c in commandes %}
<tr>
<td style="font-size:70%">({{c.temps}}){{c.epr.type}}
{% if c.epr.type == 'SNP'%}
:{{c.epr.detail}}
<img src="{{c.epr.snp.image}}" border="2" width="100" height="100"/>
</td>
{% elif c.epr.type == 'ASK' or c.epr.type == 'ANSW' %}
:<span class="{{c.epr.type}}"> {{c.epr.detail}} </span>
</td>
{% elif 
{% else %}
</td>
{% for j in c.snap %}
<!--    <td><span class={{j.action}}>{{j.action}}-{{j.change}}-{{j.JMLid}}</span></td>
  -->

<td class="u {{j.change | default:'nochange'}}"><span class={{j.action | default:"passe"}}>{{ j.commande | safe }}</span></td>
{% endfor %}
{%endif%}
</tr>
{% endfor %}
</table>

snap/templates/liste_sessions.html
{% load static %}
<script src="{% static 'snap/js/jquery-3.2.1.min.js' %}"></script> 
<script src="{% static 'snap/js/jquery-ui-1.12.1.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'snap/js/jquery-ui.css' %}">
 <style type="text/css">
 table tbody tr:hover {
    background-color: orange;
    cursor: pointer;
}
</style>
<script type="text/javascript">
  $( document ).ready(function() {      
    //console.log( "ready!" );
    $("#session").hide();
    function log( message ) {
	      $( "<div>" ).text( message ).prependTo( "#log" );
	      $( "#log" ).scrollTop( 0 );
	    }
    $.getJSON('env/users', function(data) {
	   //console.log(data);
	   $('#truc').append("<option value='0'>Tous</option>");
	   $.each(data,function (key,user){
	       console.log('user:',user.id,'-',user.eleve?user.eleve.classe:'prof');
	       $('#truc').append("<option value='"+user.id+"'>"+user.username+"("+(user.eleve?user.eleve.classe:'prof')+")"+"</option>");
	       log("ok")
	   }) ;
	   
	   
	});
    $("#envoiEleve").button().click(function(e) {
	 $.getJSON('env/'+$("#truc").val()+"/sessionsUser", function(data) {
	     //console.log(data);
	     $("#session").show();
	     $.each(data,function (key,session){
	           //console.log('user:',user.id,'-',user.eleve?user.eleve.classe:'prof');
	           $('#sessions').append("<option value='"+session.id+"'>"+(new Date(session.evenement.creation)).toUTCString()+"("+session.evenement.user+")"+"</option>");	           
	       }) ;
	     
	 })
	
    });
    $("#truc").change(function() {
	log("change"+$("#truc").val())}
    );
    $("#envoiSession").button().click(function(e) {
	   //console.log("clic"+$("#sessions").val());
	   $.get('session/'+$("#sessions").val()+"/", function(data)
		   {
	         console.log("recept"+data);
	         $( "#log" ).html(data);
	         $('table tr').click(function(){
	             alert($(this).text());
	         });
	        }
	    );
    });
  
 });
  
  

</script>

<h3>Liste des dernières sessions</h3>

  <label for="eleves">Choisir un élève: </label>
  <select  list="listeEleves" id="truc"></select>
  <datalist id="listeEleves">  
  </datalist>
  <input type="submit" id="envoiEleve">
  
  <div id="session">
  <label for="session">Choisir une sessions: </label>
  <select  list="listeSessions" id="sessions"></select>
  <datalist id="listeSessions">  
  </datalist>
  <input type="submit" id="envoiSession">
  </div>
<div class="ui-widget" style="margin-top:2em; font-family:Arial">
  Result:
  <div id="log" style="height: 400px; overflow: auto;" class="ui-widget-content"></div>
</div>
<table align="left">
{% for e in evenements %}
<tr>
<td>  </td>
<td> <div>{{e.numero}}</div><div> <span style="font-size:70%">({{e.creation}})</span></div> </td>
<td> {{e.time}} </td>
<td> {{e.type}}</td>
<td> {% for en in e.environnement.all%} {{en.type}} {{ en.detail|default:' .' }} 
    {{en.valuebool}} {{en.valueint|default:''}} {{en.valuechar|default:''}}{% endfor %}</td>
<td> {% for en in e.evenementepr_set.all %} {{en.type}} {{en.detail|default:' .'}} {% endfor %}</td>
<td> {% for en in e.evenementspr_set.all %} {{en.type}} {{en.detail|default:' .'}}
{% if en.blockId is not None%} {{en.blockId}}({{en.selector}}){% endif %}
{% if en.parentId is not None%} (p:{{en.parentId}}){% endif %}
{% if en.nextblockId is not None%} (n:{{en.nextblockId}}){% endif %}
{% if en.targetId is not None%} (t:{{en.targetId}}){% endif %}
{% if en.childId is not None%} (c:{{en.childId}}){% endif %}
 {% endfor %}</td>
</tr>
{% endfor %}
</table>
<script>
<!--
$( "input[name=file]:radio" ).change(function(){
    console.log('change',$(this).attr('id'));
    console.log('_>',$( "input[name=file]:checked" ).val());
    })
-->
</script>

snap/templates/liste_simple.html
{% load static %}

<h3>Liste des derniers évènements de {{eleve.user.username}}</h3>
<table align="left">
{% for e in evenements %}
<tr>
<td> {{e.id}} </td>
<td>  </td>
<td> <div>{{e.numero}}</div><div> <span style="font-size:70%">({{e.creation}})</span></div> </td>
<td> {{e.time}} </td>
<td> {{e.type}}</td>
<td> {% for en in e.environnement.all%} {{en.type}} {{ en.detail|default:' .' }} 
    {{en.valuebool}} {{en.valueint|default:''}} {{en.valuechar|default:''}}{% endfor %}</td>
<td> {% for en in e.evenementepr_set.all %} {{en.type}} {{en.detail|default:' .'}} {% endfor %}</td>
<td> {% for en in e.evenementspr_set.all %} {{en.id}}-{{en.type}} {{en.detail|default:' .'}}
{% if en.blockId is not None%} {{en.blockId}}({{en.selector}}){% endif %}
{% if en.parentId is not None%} (p:{{en.parentId}}){% endif %}
{% if en.nextblockId is not None%} (n:{{en.nextblockId}}){% endif %}
{% if en.targetId is not None%} (t:{{en.targetId}}){% endif %}
{% if en.childId is not None%} (c:{{en.childId}}){% endif %}
 </td>
 <td> {% if en.type == "VAL" %} {% for i in en.inputs.all %} - Changement rang {{i.rang}} par "{{i.contenu}}"{% endfor%}{% endif %}
 {% endfor %}</td>
</tr>
{% endfor %}
</table>
<script>
<!--
$( "input[name=file]:radio" ).change(function(){
    console.log('change',$(this).attr('id'));
    console.log('_>',$( "input[name=file]:checked" ).val());
    })
-->
</script>

snap/templates/snapshots.html
{% load static %}


{% for c in data %}
 <p>id: {{c.id}} <img src="{{c.image}}" border="5" width="50" height="50"/></p>


{% endfor %}